config/routes.rb
Rails.application.routes.draw do

  get "account_verification/:id" => "email_confirmation#welcome", :as => "account_verification"

  post "create_password_reset" => "password_reset#create", :as => "create_password_reset"
  resources :password_reset, only: [:new, :create, :show, :update]

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:new, :create, :destroy]

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'change_password/:id' => 'users#change_password', :as => 'change_password'
  resources :users

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/email_confirmation.rb
require "securerandom"

class EmailConfirmation < ActiveRecord::Base
belongs_to :user

validates :user_id, presence: true, uniqueness: true

before_create :set_token
before_create :set_expires_at

def to_param
  token
end

def set_token
  self.token = SecureRandom.urlsafe_base64
end

def set_expires_at
  self.expires_at = DateTime.now + 3.days
end
end

app/models/password_reset.rb
require "securerandom"

class PasswordReset < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true, uniqueness: true

  before_create :set_token
  before_create :set_expires_at

  def to_param
    token
  end

  def set_token
    self.token = SecureRandom.urlsafe_base64
  end

  def set_expires_at
    self.expires_at = DateTime.now + 3.hours
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, :uniqueness => true
  validates :email, presence: true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/email_confirmation_controller.rb
class EmailConfirmationController < ApplicationController
  def welcome
    confirm = EmailConfirmation.find_by_token(params[:id])
    @user = User.find(confirm.user_id)
    confirm.destroy
    session[:user_id] = @user.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  before_action :find_password_reset, only: [:show, :update]

  def new
  end

  def create
    email = params[:email]
    user = User.find_by_email(email)

    if user
      PasswordReset.where(user_id: user.id).destroy_all
      password_reset = PasswordReset.create(user: user)
      AccountMailer.password_reset(password_reset).deliver
    end

    redirect_to root_url, notice: "Check your email for a link to reset your password."                              
  end

  def show
  end

  def update
    if @user.update(password_params)
      @password_reset.destroy
      redirect_to root_url, notice: "Password Updated."
    else
      render :show
    end
  end

  private

  def find_password_reset
    @token = params[:id]
    @password_reset = PasswordReset.find_by_token!(@token)
    @user = @password_reset.user
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    confirm = EmailConfirmation.find_by_user_id(user.id)
    if confirm
      flash.now.alert = "You must confirm your account to log in. Check your email for an invitation."
      render "new"
    else
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, notice: "Logged in as #{user.username}"
      else
        flash.now.alert = "Invalid username or password"
        render "new"
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def change_password
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        confirm = EmailConfirmation.create(user: @user)
        AccountMailer.email_confirmation(@user, confirm).deliver
        format.html { redirect_to log_in_path, notice: 'Check your email for a notification to confirm your account.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'You succesfully updated your information.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_confirmation_helper.rb
module EmailConfirmationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/email_confirmation/welcome.html.erb
<br><br><br><div class="small-7 small-centered columns">
  <h2>Thanks for joining Chart Local!</h2>
  <p>Hi <%= @user.username %>, and thanks for joining.</p>
  <p><%= link_to "Enter", user_path(@user), class: ["button", "radius", "round", "tiny"] %></p>
</div>

app/views/home/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">

    <li class="name">
      <h1>
        <%= link_to "chart local", root_url %>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <ul class="right">
        <li class="divider"></li>
        <li class="events"><%= link_to "Log In", log_in_path %></li>
        <li class="divider"></li>
        <li class="events"><%= link_to "Log Out", log_out_path %></li>
        <li class="divider"></li>
        <li class="events"><%= link_to "Sign Up", sign_up_path %></li>
        <li class="divider"></li>
      </ul>
    </section>
</nav>

app/views/home/index.html.erb
<%= render "nav" %>

<h1>Home</h1>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "chart local" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/password_reset/new.html.erb
<br><br><br><div class ="panel small-6 small-centered columns">
  <h1>Reset your Password</h1>
  <p>An email will be sent containing instructions to reset your password.</p>

  <%= form_tag password_reset_index_path do %>
    <p class="row">
      <p class="small-1 columns"><%= label_tag :email, "email", class: "left inline" %></p>
      <p class="small-8 columns"><%= email_field_tag :email%></p>
    </p>
    <p>
      <%= submit_tag("Reset your password") %>
    </p>
  <% end %>
</div>

app/views/password_reset/show.html.erb
<div class="panel small-6 small-centered columns">
  <h1>Change your password</h1>

  <%= form_for @user, url: password_reset_path(@password_reset) do |f| %>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
    <%= f.submit("Change Password") %>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="actions">
  <%= f.submit("Update") %>
  </div>
<% end %>

app/views/users/change_password.html.erb
<br><br><br><div class="panel small-6 small-centered columns">
  <h3>Change your Password</h3>

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %></h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
    <%= f.submit("Change Password") %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<br><br><br><div class="panel small-6 small-centered columns">
  <h1>Update you information</h1>

  <%= render 'form' %>

  <br><p>
    <%= link_to "Change Password", change_password_path(@user),
        class: ["button", "radius", "round", "tiny"] %>
  </p>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Admin</th>
      <th>Options</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.admin %></td>
        <td><%= user.options %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<br><br><br><div class="panel small-6 small-centered columns">
  <h1>Sign Up</h1>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>
    <div class="actions">
    <%= f.submit("Sign up") %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Options:</strong>
  <%= @user.options %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>